language: node_js
node_js:
  - lts/boron
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ojMzLXsojFEyHaL48nrPzOy1CHtrE6E4aVMekVl2Th/HFmibODhrKeOwxWyvjEF+qj4NHV+1Yj0Nd3I7tkxCAzZl+4vXfjSVGtTvqr0wdoJ1NusvSB1uM4+/dCz8ZaUgH3XQGturWUfsemTsnvr3xPkR+XiRNzIJS7jzmaz4a3cZ2dKb8lzXYsSQDktVTEtsz4LsM2WkSHenxN9bnizMksDCdv2sL3e42kSUcWC4s9tMsJJTQMjnGb2s9WldxKuKujaIsY3kZbiG9l/jP1O1p38PI/kLp6xuQ++0wLrle3PCjUCE5wfEqCCJQhUe0fU78dTGHeXgM0L7AeXZBPmAy2A95ojKNPH2bAMuL9WFdPyiDOjI6G4tNadz6EgFvhcQyVhvM/Q90vGdZwfnvTMgT15aIA3V4sGykKCiSpW8PPQybrPRVHkplL6xu3zGgurIRd+Ve34bWAq+3YIlJvr9kcjM/349oYQNmYfCPkciAF6oUnntO8WWA88TNvOlro4Ik7e1jovHBWHJoshC28vEbFSJCsR2QztpnPwaF/Hpbi9KQdDJnnKz+mmxxfaZfwgJG/+ZWR/nno4h6sNuP4M4JD5rzT3PrfjwUGfk5dz6Il/OW2Pqa21oeaoIiHxJD7sbaeHeDMel/tvURiaTFheQF+AZkipvkby9bk/ACm9Q2UQ=
  file:
    - 'meta-name.js'
    - 'meta-name.min.js'
  on:
    tags: true
