language: node_js
node_js:
- lts/boron
- node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: T3UwZT4z3h42Qo/AMZdZHeZa5k/VhkYHOrsiiGxqc5mDnXABEFjv3KrYtQ25qmTB1nxFaiHtSxh7f3ANnLJbCCvl6Y06eaxhBluUeti5PSHrLy6DfadlyhoZ6sNCQChJhXbVoz8GMBlXA/bAWX+Wkwmel35myjJqfstbftMmjt4PpW5mFDIGWP/CZRXs0NU8rzkQ4XiDi2oyoFAi0W5phJ9xLgU9fYXKJAw8lRSTxJUDFfI+Xh63Vo2oVZOvzxy0R+PeafjfzLXtPtC6vBhiYa7fPE2qK6U65XtAPebgz6yWr6slzOsbfeQSwVGeVtdgtg0QI1ZQsGsblyVTbG+rIp2ojBztsukA3WOhALqEOkBE0t5KCqo8B3Y9FUTZEpHBrR0xm3OBRQHvzl+Qif1xLkkInrJ53VvnQ6W9jdiBH0Mzsnq9fTbfdKgZtbz9dQRIr1G2ViUiLXBOhAQu//MJAyimlb0qsqmcwe+kYfW4JIqMjCJgWqn/0KYFVQRk6bRhFOOWRh0EMuUPL4Hqb6u6Ot45eAqb5hSy+kElXQcsZhysmqhp5pLUbOxoFZAlKmfOR4laElY5dRmpuNuPwYBA7zMImyUgWlbcTFv28XIHQHkjFxwdGI7ewYIXDDYPzEaP0QJMOc7ZiKiTQv0+IO7bABtJeWVhGiZjG8zjGJGWqS0=
  file:
    - "meta-name.js"
    - "meta-name.min.js"
  on:
    tags: true
